services:
  - type: web
    name: dashboard-dhl
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    disk:
      name: dhl-db
      mountPath: /data
      sizeGB: 1
